all: vectorSumInt vectorSumDouble

vectorSumInt: vectorSum_int.c
	gcc vectorSum_int.c -o vectorSum_int

vectorSumDouble: vectorSum_double.c
	gcc vectorSum_double.c -o vectorSum_double

clean:
	rm -f vectorSum_int vectorSum_double
